[DEFAULT]
#======== Database Properties =============#

DATABASE_URL =
BUCKET =
DB_PASSWORD =
INFLUXDB_TOKEN =
USERNAME =
INFLUX_PASSWORD =
ORG =
HISTORIC_MARKET_DATA_INFLUX =

#======== Google Drive Market Data =============#

GDRIVE_DESTINATION_PATH =
GDRIVE_MARKET_DATA_TO_UPLOAD =
ZIPPED_MKTDATA_TO_UPLOAD =
TBILL_MARKET_DATA =
CHROME_DRIVER_PATH =
TOKEN_MAPPING_PATH =
PICKLE_DATA_OUTPUT =

#======== Token Mapping keys =============#
NIFTY =
BANKNIFTY =
FINNIFTY =

#======== Web Scraping =============#

ccil.scraping.url =

#======== Smart Api=============#

apikey =
clientCode =
pwd =
token =

#========kafka=============#

boostrap.servers =
smartApi.liveMarketData =
smartApi.greekCalculator =
group.id =

#---------Rate Streaming-----------------#
batch_size =

#========Amazon Web Services=============#
s3bucket =

#========Redis=============#
redis.server.port =
